# Generated by Django 3.1.3 on 2020-12-15 04:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTable',
            fields=[
                ('account_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('SA', 'saving account'), ('FDA', 'fixed deposit account')], max_length=4)),
                ('balance', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('branch_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=56)),
                ('branch_city', models.CharField(max_length=80)),
                ('branch_country', models.CharField(max_length=50)),
                ('branch_phone', models.CharField(max_length=12)),
                ('manager_number', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContactTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.CharField(max_length=25)),
                ('contact_lastname', models.CharField(max_length=25)),
                ('contact_country', models.CharField(max_length=30)),
                ('contact_message', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('customer_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=128)),
                ('customer_address', models.CharField(max_length=256)),
                ('customer_phone_no', models.CharField(max_length=14, unique=True)),
                ('customer_email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_stamp', models.DateTimeField(default=datetime.datetime(2020, 12, 15, 9, 51, 4, 846484))),
                ('credit_or_deposit', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.IntegerField()),
                ('trans_account_number_id_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankdb_app.accounttable')),
                ('trans_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankdb_app.customertable')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.PositiveIntegerField(unique=True)),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('employee_address', models.CharField(max_length=256)),
                ('employee_phone_no', models.CharField(max_length=14)),
                ('employee_email', models.EmailField(max_length=50)),
                ('employee_qualification', models.CharField(max_length=40)),
                ('branch_id_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='bankdb_app.bankbranch')),
            ],
        ),
        migrations.AddField(
            model_name='accounttable',
            name='customer_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankdb_app.customertable'),
        ),
        migrations.AddField(
            model_name='accounttable',
            name='which_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankdb_app.bankbranch'),
        ),
    ]
