# Generated by Django 3.1.3 on 2020-12-18 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankdb_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiontable',
            old_name='credit_or_deposit',
            new_name='credit_or_debit',
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='employee_email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transactiontable',
            name='date_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 23, 20, 13, 988661)),
        ),
    ]
