# Generated by Django 3.1.3 on 2020-12-26 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankdb_app', '0002_auto_20201218_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontable',
            name='date_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 16, 33, 26, 186406)),
        ),
    ]
