# Generated by Django 3.1.3 on 2020-12-26 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankdb_app', '0003_auto_20201226_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontable',
            name='date_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 16, 34, 13, 911927)),
        ),
    ]
