# Generated by Django 3.1.3 on 2020-12-26 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankdb_app', '0004_auto_20201226_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontable',
            name='date_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 16, 36, 12, 236839)),
        ),
    ]
