# Generated by Django 3.1.3 on 2021-09-10 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankdb_app', '0006_auto_20201226_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontable',
            name='date_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 10, 10, 24, 55, 253526)),
        ),
    ]
